import type { MatchHistoryResponse } from "./types";

export const matchData: MatchHistoryResponse = {
  data: {
    matchHistory: {
      matches: [
        {
          date: "2025-09-25T19:13:56.000Z",
          map: 17,
          duration: 692094,
          mode: 2,
          season: 2,
          is_ranked: 1,
          is_competitive: 1,
          match_history_processed: 1,
          region: 3,
          historyEntries: [
            {
              accuracy: 44,
              assists: 15,
              damage_done: 6092,
              deaths: 42,
              headshots: 25,
              kills: 48,
              objective_score: 1260,
              score: 7280,
              team: 2,
              player_name: "Auspicious",
              rank: 9,
              mmr_change: -26,
            },
            {
              accuracy: 46,
              assists: 19,
              damage_done: 5880,
              deaths: 41,
              headshots: 27,
              kills: 55,
              objective_score: 1450,
              score: 8650,
              team: 1,
              player_name: "Duprious",
              rank: 5,
              mmr_change: 87,
            },
            {
              accuracy: 30,
              assists: 20,
              damage_done: 5042,
              deaths: 43,
              headshots: 19,
              kills: 46,
              objective_score: 900,
              score: 6540,
              team: 2,
              player_name: "gimooooo",
              rank: 6,
              mmr_change: -42,
            },
            {
              accuracy: 32,
              assists: 20,
              damage_done: 5375,
              deaths: 44,
              headshots: 25,
              kills: 42,
              objective_score: 850,
              score: 6500,
              team: 2,
              player_name: "Naturalj",
              rank: 0,
              mmr_change: 0,
            },
            {
              accuracy: 22,
              assists: 14,
              damage_done: 2401,
              deaths: 42,
              headshots: 7,
              kills: 20,
              objective_score: 1330,
              score: 3865,
              team: 2,
              player_name: "Bibou-FR",
              rank: 5,
              mmr_change: -37,
            },
            {
              accuracy: 17,
              assists: 20,
              damage_done: 2798,
              deaths: 38,
              headshots: 11,
              kills: 19,
              objective_score: 1240,
              score: 3975,
              team: 1,
              player_name: "crossyroad-_-",
              rank: 5,
              mmr_change: 86,
            },
            {
              accuracy: 26,
              assists: 16,
              damage_done: 3691,
              deaths: 45,
              headshots: 16,
              kills: 37,
              objective_score: 1080,
              score: 5735,
              team: 1,
              player_name: "hamid010",
              rank: 4,
              mmr_change: 86,
            },
            {
              accuracy: 35,
              assists: 16,
              damage_done: 6352,
              deaths: 32,
              headshots: 36,
              kills: 60,
              objective_score: 1220,
              score: 9010,
              team: 1,
              player_name: "Iage",
              rank: 8,
              mmr_change: 57,
            },
          ],
          score_alpha: 2,
          score_bravo: 1,
        },
        // ... other matches can be added here
      ],
      totalPages: 2,
    },
  },
};
